exclude: >
  (?x)(
      docs/|
      node_modules/
  )
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
- repo: https://github.com/myint/autoflake
  rev: v1.7.7
  hooks:
  - id: autoflake
    exclude: &fixtures tests/functional/|tests/input|tests/extensions/data|tests/regrtest_data/|tests/data/|__init__.py
    args:
    - --in-place
    - --remove-all-unused-imports
    - --expand-star-imports
    - --remove-duplicate-keys
    - --remove-unused-variables
- repo: https://github.com/asottile/pyupgrade
  rev: v3.2.0
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
    exclude: docs*
    additional_dependencies: [toml]
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: pretty-format-ini
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
repos:
  - repo: https://github.com/christopherpickering/pre-commit-hooks
    rev: 0.0.6
    hooks:
      - id: poetry-to-requirements
        args: [--output=requirements.txt]
