[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool]

[tool.poetry]
name="djlint"
version="1.19.6"
description="HTML Template Linter and Formatter"
license="GPL-3.0-or-later"
authors=["Christopher Pickering <cpickering@rhc.net>"]
maintainers=["Christopher Pickering <cpickering@rhc.net>"]
readme="README.md"
repository="https://github.com/Riverside-Healthcare/djlint"
documentation="https://djlint.com"
classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
        "Operating System :: OS Independent",
    ]
packages = [
    { include = "djlint", from = "src" },
]
include = ["rules.yaml"]

[tool.poetry.dependencies]
python = "^3.7.2,<4.0"
click = "^8.0.1"
PyYAML = "^6.0"
colorama = "^0.4.4"
regex = "^2022.1.18"
tqdm = "^4.62.2"
tomli = { version = "^2.0.1", python = "<3.11" }
pathspec = "^0.10.0"
importlib-metadata = "^5.0.0"
html-void-elements = "^0.1.0"
html-tag-names = "^0.1.2"
jsbeautifier = "^1.14.4"
cssbeautifier = "^1.14.4"
html-template-parser = "^1.6.0"
html-element-attributes = "^0.1.2"
html-styles = "^0.1.2"


[tool.poetry.dev-dependencies]
black = "^22.1.0"
isort = "^5.9.3"
coverage = "^6.4.2"
pytest = "^7.1.2"
pytest-cov = "^4.0.0"
pytest-xdist = "^3.0.0"
pylint = "^2.14.5"
mypy = "^0.982"
types-PyYAML = "^6.0.11"
pep8-naming = "^0.13.1"
tox = "^3.25.1"
pylint-per-file-ignores = "^0.1.0"

[tool.poetry.scripts]
djlint = "djlint:main"

[tool.black]
max_line_length = 99
quiet = true

[tool.isort]
profile = "black"
quiet = true

[tool.mypy]
ignore_missing_imports = true

[tool.pylint.messages_control]
disable = "E1120, R0914, E0401, R0912, R0916, R0913, W0104, R0801, W1404, R0902, R0903, R1732, R0915, C0301, R1702"

[tool.pylint.TYPECHECK]
ignored-modules = "regex"

[tool.pylint.MASTER]
load-plugins=[
    "pylint_per_file_ignores"
]
ignore="tests/pylint_plugins"

[tool.pylint-per-file-ignores]
"/tests/"="missing-function-docstring,W0621,W0240,C0115,C0103,W1404"
